receivers: # データ発生源
  otlp:
    protocols:
      grpc:

processors: # データ加工
  batch:

exporters: # 出力先
  otlp/jaeger: # otlp/<sukina_namae>
    endpoint: jaeger:4317
    tls:
      insecure: true

  otlp/newrelic:
    endpoint: https://otlp.nr-data.net:4317
    headers:
      api-key: NEW_RELIC_API_KEY 

service: # ここがメインの設定
  pipelines:
    traces:  # traceたちを
      receivers: [otlp] # otlpで受け取り
      processors: [batch] # batchで加工し
      exporters: [otlp/jaeger, otlp/newrelic] #jaegerとnewrelicに送る
